### ISSUE TITLE
Add Identifier

### ISSUE THREAD

**Issue by thomaskolmans** [opentripmodel/otm5-change-requests#15]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
In case of integrations, knowing another systems ID or where an object has been sent is important. There is no ideal or good solution for this in OTM yet in our opinion. You could put those in `externalAttributes` but this should not be the intent. 

**Describe the solution you'd like**
In the health industry they have this as an Identifier (https://www.hl7.org/fhir/datatypes.html#Identifier). We would propose the same thing, we've already implemented this actually. 

**Describe alternatives you've considered**
You could put those in `externalAttributes` but this should not be the intent.

**Comment by bmeesters** [comment]
@thomaskolmans could you maybe provide an example JSON to make it a bit more clear exactly what you want. We also might need to think about the name since it can be confusing to have both an ID and UUID.

**Comment by thomaskolmans** [comment]
Absolutely. So we would like to introduce the following: 

```
{
    name: 'the name of the identifier', 
    system: 'system where this identifier is used',
    value: 'the actual identifier',

   startsAt: 'the date this identifier came to life',
   expiresAt: 'optional date when this identifier is no longer valid', 

   assigner: ActorAssocation
}
```

One more time the reasoning for this; let's say a location is taken over by another system, they will most likely generate a new UUID for this location in their own format. Or at least, we would. However, we would still like to know how they are referencing it. 

An example. A vehicle is created within a system, has an integration with a board-computer where it has a different identifier, you would still want to communicate this identifier. This could be important or good information for external parties or integrations.

**Comment by bmeesters** [comment]
Thanks for the example. Just for your information. We will come back on this topic. We are going to release OTM5.1 tomorrow, so we need some more time to finish that up. Then we can take the time to come back to the other open issues.

**Comment by bmeesters** [comment]
Hello @thomaskolmans, sorry to get back to you a bit later. It has been a busy time in releasing OTM5.1. I understand the need, but I also have some doubts about the proposal.

We cannot name the field `id`, since every entity already has an ID field for the UUID. It would also be confusing on when to use which. Also what would be the leading ID? the UUID or the value in the block you use? We introduced UUIDs in OTM to get rid of string or number IDs as the leading identifier. You can still use them, but only as external attributes. That is exactly why they were made.

> One more time the reasoning for this; let's say a location is taken over by another system, they will most likely generate a new UUID for this location in their own format. Or at least, we would. However, we would still like to know how they are referencing it.

I wonder why you do this though. The whole point of a 'universally unique identifier' is that it is universally unique, so you can just reuse the UUID from the source you get it from. There is no reason (I think) to just generate a new one.

I think it would be good to add a 'source/system' so you know where a message originated from, but other than that I rather not promote another way of creating IDs that can be used through each other. 

That said, if you have more arguments, or other people you know who would also benefit from this change you can ping them and ask them to promote this change request here. I'll ask around with other parties as well. But I think we would need to see more clearly how this operates in between the current leading UUIDs and ensure there is no confusion.

**Comment by thomaskolmans** [comment]
Hi @bmeesters, 

Understand your argumentation. My argumentation is that when integrating with systems, with or without OTM, different UUID (or ID's) will be used. 

As an example, our board-computer integrations. They are referencing the same vehicles as the "system" is, but with an entirely different identifier structure and value. If we where to communicate our Vehicle object we would also like to communicate that we've "connected" to this vehicle and it's identifier. 

That is one use-case that we for instance use for these Identifier objects.

**Comment by bmeesters** [comment]
Yes I do understand why you would want to communicate other IDs than those that are present in the UUIDs. However I think there is not that big of a difference between:

```json
{
  "entityType": "trip",
  "id": "<some uuid>",
   "identifier": {
     "name": "externalSystemId", 
     "system": "mySystem",
     "value": "myId1234",
   },
// other fields
}
```

and 

```json
{
  "entityType": "trip",
  "id": "<some uuid>",
   "externalAttributes": {
     "externalSystemId": "myId1234", 
     "system": "mySystem",
   },
// other fields
}
```

Other than the fact that your current proposal also includes a time range for the identifier and a system where it originated from. I think adding the system where it originated from is a good idea. I just don't think we need the name/value attributes in the `identifier` object. Since those can also be added in the externalAttributes. This is also why they were made and how they are also already used in OTM4 (where they were called `externalIds`).

To avoid having the option to do the same thing in multiple ways I don't think we should add an `identifier` field.

**Comment by thomaskolmans** [comment]
Except the minor difference being that with an Identifier object you can make it an array of values. When integrating with multiple systems this becomes necessary in my opinion.  If that is not a consideration I understand not adding it.

**Comment by bmeesters** [comment]
> Except the minor difference being that with an Identifier object you can make it an array of values. 

I am sympathetic to this point of view. I do think this is currently not well supported. I would preferably see that systems just use the one and only UUID, since that is what is meant for. It is not universally unique for nothing. But I am aware that is wishful thinking.

Not sure though whether we want to introduce a new ID object because of the earlier mentioned downsides (confusing w.r.t. the UUID, might encourage using many different IDs instead of the UUID).

I'll leave this open for the time being and ask around. You can choose whether you want to extend the OTM you send with this data of course. Since it is just JSON you are not violating the standard. But I am not sure whether it will be part of the standard.

**Comment by thomaskolmans** [comment]
Totally understand that too, we're already using it, wanted to at least bring it in as a suggestion and the reasoning why we're using it. 

If you have any further questions or concerns, let me know!

**Comment by BobZuidhoek** [comment]
Do note that there already is a global system to assign ID's to physical locations, which is the GLN (Global Location Number). GLN's are already used a lot. Nearly all professional businesses that operate large logistics locations (such as warehouses), already have a unique GLN-number registered. 

For other addressees that are not registered as GLN, the correct unique identification of addresses is indeed problematic. I think it's still relies on comparing country/postal-code/house-number logic and stuff like that.

**Comment by bmeesters** [comment]
I am still sympathetic to the idea of communicating the different IDs that are involved through multiple systems. That said, I don't think it is common enough to add something that could also lead to confusion and be abused. In the end we _want_ that users use the UUID, which is globally unique for a reason. Naturally not all systems will do this, but for that the external attributes can be used. This might be a little quirky, but workable. I am going to close this now since we will not add this any time soon. If the request comes in again via other channels I'll be sure to tag you.
