### ISSUE TITLE
Make ADR documentation clearer

### ISSUE THREAD

**Issue by rverberne** [opentripmodel/otm5-change-requests#18]
**Type of bug**
- [ ] Inconsistency or contradiction in the specification
- [ ] Fault in the representation (rendering) of the specification
- [X] Other (please describe below)

**General**
- None of the adr fields have a description.
- No example values are given.

**language**
It is not clear why this is required.

**description & technicalName**
To me personally at first it was not clear what the difference is. Because the official ADR list has a column named `Name and description` this can be confusing. The technical name is something you can _add_ to the `Name and description` and is not somehow contained in that column. More documentation and example values could make this clear.

| UNNumber| description | technicalName |
|----------|-------------|---------------|
|2902    |PESTICIDE, LIQUID, TOXIC, N.O.S.             |(DRAZOXOLON)|
|3394    |ORGANOMETALLIC SUBSTANCE, LIQUID, PYROPHORIC, WATER-REACTIVE|(TRIMETHYLGALLIUM)|
|3540     |ARTICLES CONTAINING FLAMMABLE LIQUID, N.O.S.|(PYRROLIDINE)|
|1993     |FLAMMABLE LIQUID, N.O.S|(CONTAINS XYLENE AND BENZENE)|

**class**
What do valid values look like (`8`, `3`, `6.1`)? Example values would help. Is this a candidate for an enum?

**classificationCode**
What do valid values look like (`F1`, `FT1`, `FC`, `CF1`)? Example values would help. Is this a candidate for an enum?

**packagingGroup**
There are 3 possible values that i know of (`I`, `II`, `III`). Why is this not a enum?

**dangerLabels**
What do valid values look like (`4.1`, `4.2`, `6.1`)? Example values would help. Is this a candidate for an enum?

**dangerNumber**
A real word example would be nice. For example:

| UNNumber | dangerNumber | description |
|----------|-------------|---------------|
|1202| 30 |GAS OIL or DIESEL FUEL or HEATING OIL, LIGHT (flash-point not more than 60 °C)|

**tunnelCode**
What do valid values look like (`D/E`, `C/D`, `B/D`, `E`)? Example values would help. Is this a candidate for an enum?

**Comment by bmeesters** [comment]
You are completely right @rverberne. I unfortunately cannot answer these questions since I do not know enough about ADRs. I will check with @woutvandenheuvel and Menno Lambooy if they can help me with this.

**Comment by woutvandenheuvel** [comment]
@rverberne @bmeesters I made a first start with adding description and information to the ADR section. This input will be reviewed as well by some experts on ADR.


<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/WVDHEU~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/WVDHEU~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/WVDHEU~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<p class="MsoNormal"><o:p>&nbsp;</o:p></p>


&nbsp; | Official ADR documentation is published &nbsp;on [ADR 2021 (files) \| UNECE](https://unece.org/transportdangerous-goods/adr-2021-files). Used descriptions in OTM   documentation are extracted from document ADR2021_Vol1e_0.pdf [(unece.org)](https://unece.org/sites/default/files/2021-01/ADR2021_Vol1e_0.pdf) Official documentation is always   leading and should be consulted
-- | --
Un Number | Central to the use of the restructured   ADR is table A of Chapter 3.2 in document ECE/TRANS/300 which contains the   dangerous goods list in the numerical order of UN numbers.
Language | Marks shall be in an official language   of the country of origin and also, if that language is not English, French or   German, in English, French or German, unless agreements, if any, concluded   between the countries concerned in transport operations provide otherwise
Name and description | Contains in upper case   chararacters, the name of the substance or article, if the substance or   article has been assigned its own specific UN number, or otherwise the proper   shipping name shall be used. See 3.1.2 for further details
Technical name | The technical name which shall   supplement the proper shipping name shall be the ISO common name.    A recognized chemical name, if   relevant a biological name, or other name currently used in scientific and   technical handbooks, journals and texts. (see 3.1.2.8.1.1 &nbsp;ADR2021_Vol1e_0.pdf (unece.org)
Waste | Indicator to be used in case commodity   is classified as waste
Environmentally   hazardous | Indicator to be used to label   waste as environmentally hazardous.
Class | Number of the class, whose heading   covers the dangerous substance or article.    2.1.1.1 The classes of dangerous   goods according to ADR are the following   &nbsp;   Class 1 &nbsp;&nbsp;&nbsp;&nbsp;Explosive substances and articles   Class 2 &nbsp;&nbsp;&nbsp;&nbsp;Gases   Class 3 &nbsp;&nbsp;&nbsp;&nbsp;Flammable liquids   Class 4.1 Flammable solids, self   reactive substances, polymerizing substances and &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; solid desensitized explosives   Class 4.2 Substances liable to   spontaneous combustion   Class 4.3 Substances which, in   contact with water, emit flammable gases   Class 5.1 Oxidizing substances   Class 5.2 Organic peroxides   Class 6.1 Toxic substances   Class 6.2 Infectious substances   Class 7&nbsp;&nbsp;&nbsp; Radioactive material   Class 8&nbsp;&nbsp;&nbsp; Corrosive substances   Class 9&nbsp;&nbsp;&nbsp; Miscellaneous dangerous substances and   articles
Classification   code | The classification code of the dangerous   substance or article. The code consists out of a division number and   compatibility group letter depending on the class
Packing group | Packing Group means a group of   which, for packing purposes, certain substances may be assigned in accordance   with their degree of danger.    Packing group values: I, II and III
labels | The model number(s) of the labels/placards   (see 5.2.2.2 and 5.3.1.7 &nbsp;ADR2021_Vol1e_0.pdf (unece.org)) that have to be affixed to   packages, containers, tank containers, portable tanks, MEGC’s and vehicles
Special provisions | Contains the numeric codes of special provisions that have to be met. Listed   in Chapter 3.3 ADR2021_Vol1e_0.pdf   (unece.org)
Danger number | &nbsp;
Tunnel restriction   code | Code to indicate tunnel category where   restrictions apply to the passage of vehicles carrying dangerous goods. Categories   A.B.C.D. and E as defined in 1.9.5.2.2. ADR2021_Vol1e_0.pdf (unece.org)






Examples




<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/WVDHEU~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/WVDHEU~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/WVDHEU~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>







UN Number | Language | Name and description | Class | Classification | Packing Group | Labels | Special provisions | Waste | Environmental hazardous | Tunnel Code
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1133 | English | ADHESIVES containing flamable liquids | 3 | F1 | III | 3 | &nbsp; | False | True | A
1017 | English | Chlorine | 2 | 2TOC | &nbsp; | 2.3+2.1+8 | &nbsp; | FALSE | True | A

**Comment by rverberne** [comment]
That is a good start voor the documentation.

Right now we can process the following json:

```json
"adr": {
  "UNNumber": "3540",
  "language": "EN",
  "description": "ARTICLES CONTAINING FLAMMABLE LIQUID, N.O.S.",
  "technicalName": "PYRROLIDINE",
  "waste": false,
  "environmentallyHazardous": true,
  "class": "3",
  "classificationCode": "F3",
  "packagingGroup": "III",
  "dangerLabels": [ "3", "6.1" ],
  "dangerNumber": "30",
  "tunnelCode": "E"
}
```

It would be nice to standardise things like `dangerLabels` and the the other fields.

**Comment by bmeesters** [comment]
@woutvandenheuvel did you get some feedback on your proposal from experts within the ADR field? I can update the documentation whenever we find it good enough (and we can also update it later).

**Comment by bmeesters** [comment]
I have used the documentation provided and put it on the beta website: https://otm5-documentation-api-dev.redoc.ly/#tag/Goods/paths/~1api~1v5~1goods/put

The next step would be to limit the options you have for certain fields (make them enums instead of free text).

**Comment by bmeesters** [comment]
I have updated the documentation. In the future we can also tighten some values like danger labels or classes. But I think this would be sufficient for now since we have some actual documentation.

**Comment by rverberne** [comment]
The `tunnelCode` field has no documentation. The `dangerNumber` field has documentation, but that looks like it was meant for `tunnelCode`. Is this correct?

**Comment by bmeesters** [comment]
Yes you are right, I made a mistake. Will swap the documentation.

The danger number has no documentation above, so I cannot fill it in.
