### ISSUE TITLE
Event documentation is inconsistent for updateEvent

### ISSUE THREAD

**Issue by MrGroovy** [opentripmodel/otm5-change-requests#3]
**Type of bug**
- [X] Inconsistency or contradiction in the specification
- [X] Fault in the representation (rendering) of the specification
- [ ] Other (please describe below)

**Describe the bug**
* The documentation for Event (type updateEvent) is inconsistent
    * transportOrder is missing
    * transportEquipment does not exist
    * items does not exist
    * goods is missing
* The documentation for Event is buggy
    * Changing the value of the entityType combobox will make it disapear.

**Comment by bmeesters** [comment]
Hello @MrGroovy, thanks for your contribution. I verified and indeed the documentation is incorrect & the switching is buggy. For a little context, Goods can be divided into Items and TransportEquipment. And the documentation incorrectly references those instead of Goods itself. So Items and TransportEquipment do exist, but only as a sub-type of Goods.

I'll look into it next week.

**Comment by bmeesters** [comment]
@MrGroovy, turns out this change was harder than I expected and requires a bit of a workaround. I made a beta here: https://otm5-documentation-api-dev.redoc.ly/#tag/Event/paths/~1api~1v5~1events/put. That said, we might need to think about how to change UpdateEvent to properly deal with goods (since it uses a double discriminator). But for now I think this is good enough.

**Comment by bmeesters** [comment]
The fix is on otm5.opentripmodel.org. Thanks again for reporting this.
