### ISSUE TITLE
Add `hscode` to Items

### ISSUE THREAD

**Issue by thomaskolmans** [opentripmodel/otm5-change-requests#35]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec

**Describe the solution you'd like**
Add the field `hscode` to the `Items` object (subtype of `Goods`). In our opinion this is a standardised value that shouldn't belong in the `externalAttributes` and has a place in the `Items` in a standardised model.

**Describe alternatives you've considered**
`externalAttributes` fields

**Comment by bmeesters** [comment]
Hello Thomas,

Yes we agree, though note that this discussion is already in place, see also https://github.com/opentripmodel/otm5-change-requests/issues/26

The idea is to add new 'classification' lines that include the HS code. If you have any thoughts about this please leave them there.

I'll close this ticket since it is a duplicate and we can better track the progress in one ticket.

**Comment by bmeesters** [comment]
No problem, feel free to leave any feedback there!
