### ISSUE TITLE
Add a TotalInvoiceAmount within a Consigment

### ISSUE THREAD

**Issue by rvanweegberg** [opentripmodel/otm5-change-requests#47]
In some Consignments an agreed Transportprice needs to be added. This Transportprice is a Total of all Freight Charges.

**Comment by bmeesters** [comment]
Hello @rvanweegberg, thanks for contributing to OTM. Could you extend your request with more details? What should the transport price look like exactly? Is there only one? Does there need to be a difference between gross and net prices? Do we need to be able to split the price in sub prices to show how the total price came to be (for example because the consignment travels along multiple trips)? Ideally your request comes with an OTM to-be example that can be discussed.

**Comment by rvanweegberg** [comment]
It can be one amount: TotalInvoiceAmount. This can be seperated in gross and net. Currency should be added according to Currency codes (ISO 4217). Following example:

"TotalInvoiceAmount": {
"gross price": 605.00,
"VAT rate": 21.00,
"net price": 500.00,
"currency": "EUR"
},

**Comment by thomaskolmans** [comment]
Like this suggestion as a bases but I would like to extend the discussion upon pricing into a broader format. Not only in relation to Consignment but in relation to any part that may have some form of cost involved.

**Comment by bmeesters** [comment]
I agree that it is better to take it broader than consignment, and in fact, we already have a _change request_ for that. See https://github.com/opentripmodel/otm5-change-requests/issues/21. Thus I am closing this one and we can continue discussing there.

**Comment by woutvandenheuvel** [comment]
Agree. A broader discussion on pricing is needed. We are planning a OTM workshop in January 2022. I suggest we spend some time on this topic in that session. We can use this item as an example and as input for this workshop.
