### ISSUE TITLE
Add mobilePhone as contact detail type

### ISSUE THREAD

**Issue by gerardpeters** [opentripmodel/otm5-change-requests#5]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
The model contains the field phone number. There is no clear distinction between a landline and a mobile phone number. For example for sending text messages or voice messages this is information we would like to know.

**Describe the solution you'd like**
An extra contact details type 'mobilePhone'.

**Describe alternatives you've considered**
Use the phone number, but then you can't provide both phone number and mobile phone number.

**Comment by bmeesters** [comment]
Thanks for your contribution @gerardpeters.

We are how exactly you want to use this information. Note that it is currently possible to provide multiple contact-details and use the same type of contact detail with a remark. For example:

```
{
  "id": "3f80d380-ca82-495a-9d66-5b220cd293e3",
  "contactDetails": [
    {
      "value": "0612345678",
      "remark": "mobile",
      "type": "phone"
    },
    {
      "value": "0118123456",
      "remark": "landLine",
      "type": "phone"
    }
  ]
}
```

This is of course not ideal if you _need_ to know exactly what kind of phone you are using since it might contain typos, and you might want to use the remark for something else as well. But that is really only a problem if you are expecting to act on this information automatically.

We could also consider adding a few sub-types of the contact-detail type, such as a `phoneType` and `emailType`. However this will likely result in another union type to avoid having an `emailType` on a `phone` contact detail.

Maybe if you provide us with some more information on your use case we can look at the alternatives?

**Comment by gerardpeters** [comment]
We use the mobile number to send automated text messages based on the status of a consignment or events that are happening. We also have to ability to send text to voice messages to a landline. Because these messages are more expensive and not everybody wants to use this feature we need a clear distinction between the types of phone numbers. 

Mapping based on magic strings (remark) is far from ideal since we cannot enforce a value based on the scheme. Whereas the type as enum has an enforcement.

**Comment by bmeesters** [comment]
Yes I agree, for such an advanced use case a magic string is not sufficient.

I think the best way forward would be to identify types per contact detail. So the `phone` contact detail has a `phoneType` that exists of an enum with `landLine` and `mobile` (and potentially more in the future).

Is this acceptable for you?

**Comment by gerardpeters** [comment]
That would work, I'm not really sure if that change can be backwards compatible with the current model, but if that's the case I'd like to see this in a future version!

**Comment by bmeesters** [comment]
If the new fields are optional the JSON will be backwards compatible, though the OpenAPI specification needs to change a bit to make it possible. Need to check to be sure though. I'll make this suggestion will be discussed again at the next meeting.

**Comment by bmeesters** [comment]
@gerardpeters, sorry to get back to you so late. We had another discussion and will go with your original approach (so add a new contact detail option). It will be included in OTM5.1

**Comment by bmeesters** [comment]
Closing this as it is now official part of OTM5.1
