### ISSUE TITLE
Make fuel an enum instead of a free form string

### ISSUE THREAD

**Issue by ptv-jcl** [opentripmodel/otm5-change-requests#51]
**Type of request**
- [ ] I'd like to add something to the OTM 5 spec
- [x] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
Currently vehicle.fuel and fuelTypeConstraint.fuelTypes accept freeform strings. This can lead to inconsistencies when comparing the 2. For example bezine , petrol, gasoline and gas are all synonyms for the same fuel type.

**Describe the solution you'd like**
I would like to see this become an enum. Values proposal:
* petrol
* diesel
* electricity
* hydrogen
* lng
* cng
* not-applicable 
* other

**Describe alternatives you've considered**

**Additional context**

**Comment by bmeesters** [comment]
Yes, I am in favor of adding these kind of enums in multiple places, where other + an optional field where the other can be specified as fallback. I will discuss this tomorrow in the weekly SUTC meeting we have

**Comment by bmeesters** [comment]
This has been open for a while since it did not get much priority. TNO is currently working on various 'enums' in the field. Such as vehicle categories, consignment types, transport equipment type, etc. We are working on integrating that in OTM5 once finished. This will remain dormant until TNO is a bit further.

**Comment by bmeesters** [comment]
Suggestion: also add addblue for diesel

`diesel` and `addblue`
