### ISSUE TITLE
Additional actorRole

### ISSUE THREAD

**Issue by etwobben** [opentripmodel/otm5-change-requests#67]
**Type of request**
- [x] I'd like to add something to the OTM 5 spec
- [ ] I'd like to change something in the OTM 5 spec

**Is your feature request related to a problem?**
We are missing an actorRole we would like to add to the specification. Some clients of ours have a set of underlying company names under which they are selling their goods. The consignor would still be the main company, but to the person that receives the goods that name would mean nothing, because they order with the sub company. The name of the sub company would appear on the delivery note. 

**Describe the solution you'd like**
An extra actorRole should solve all our problems. Not sure about the name though, but maybe something like WhitelabelPartner should be good enough. Open to other suggestions :-)

**Describe alternatives you've considered**
We could use the sub company as the main consignor, and somewhere in our backend keep a tree of organizations to determine the main company, but then OTM wouldn't contain all the needed data.

**Additional context**
-

**Comment by bmeesters** [comment]
Hello @etwobben, thanks again for trying to improve the specification.

We talked about it in a larger setting and we would like to understand the use case a bit better. Wouldn't it be possible to either just use the actual company, or the white label name as the actor name? Is it truly necessary to indicate that the front is not the actual company?

We are a little afraid that this is a slippery slope since it is a very specific use case, which opens the doors for many other type of very specific actor roles. Which ultimately will result in a more bloated, hard to understand specification.

Some things that might help achieve your goals:
* You can add an external attribute to the actor, to indicate that it is not the actual company byt a WhiteLabelPartner.\
* You can add a description to every association, which could be used to fill this data

See the specification for more details:

![image](https://user-images.githubusercontent.com/32057771/206184397-795c7bc2-4add-42d9-8cf7-0c1915307f70.png).

I understand this might not be the most desirable outcome for you, but would it be workable?

**Comment by bmeesters** [comment]
Closing this since a lack of response and we currently do not have a good alternative yet.
